<?php

/**
 * @file
 * File conversion provided by ImageMagick PHP extension.
 *
 * @see http://www.php.net/manual/en/class.imagick.php
 */

/**
 * Implements of hook_menu().
 */
function cf_imagemagick_menu() {
  // Provide a page to handle watchdog error messages.
  $items['admin/config/convertfile/settings/provider/imagemagick'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'ImageMagick',
    'description' => 'File conversion provided by ImageMagick.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cf_imagemagick_form'),
    'access arguments' => array('administer convertfile settings'),
    'file' => 'cf_imagemagick.admin.inc',
    'file path' => drupal_get_path('module', 'cf_imagemagick'),
    'weight' => 40,
  );

  return $items;
}

/**
 * Implements hook_convertfile_info().
 *
 * Register our provider and formats with convertfile module.
 *
 * @see convertfile_collect_info()
 */
function cf_imagemagick_convertfile_info() {
  return array(
    // Preface array structure with module machine name.
    'cf_imagemagick' => array(
      // Human friendly name of provider.
      'name' => 'ImageMagick',
      // Extensions that this provider will convert to.
      'types' => array(
        'png' => '.png (image/png)',
        'jpg' => '.jpg (image/jpeg)',
      ),
      // Provider specific options callback (optional).
      'options' => 'cf_imagemagick_options',
      // Provider specific options submission formatter callback (optional).
      'exposed_options' => 'cf_imagemagick_options_exposed',
      // Friendly link for help with this provider (optional).
      'help' => array(
        'url' => 'https://github.com/delphian/drupal-convert-file/wiki/ImageMagick',
      ),
    ),
  );
}

/**
 * Custom options callback.
 *
 * Create render array for conversion options unique to ImageMagick. These
 * options will be displayed when editing the field structure of a field that
 * uses the convertfile widget and ImageMagick as the provider.
 *
 * Render array key names must be prefaced with the module name.
 *
 * @param string $format
 *   The format that is currently selected.
 * @param array $specific
 *   The portion of the form containing provider specific configuration data.
 *
 * @todo Create an alter hook for this, place another for actdual IM processing.
 * @see cf_imagemagick_convertfile_info()
 */
function cf_imagemagick_options($format, $specific = NULL) {
  $im = isset($specific['cf_imfs']) ? $specific['cf_imfs'] : NULL;
  $im_setresolution = isset($im['cf_imagemagick_opt_setresolution']) ? $im['cf_imagemagick_opt_setresolution'] : NULL;
  $im_resizeimage = isset($im['cf_imagemagick_opt_resizeimage']) ? $im['cf_imagemagick_opt_resizeimage'] : NULL;
  $im_setcompressionquality = isset($im['cf_imagemagick_opt_setcompressionquality']) ? $im['cf_imagemagick_opt_setcompressionquality'] : NULL;
  $im_appendimages = isset($im['cf_imagemagick_opt_appendimages']) ? $im['cf_imagemagick_opt_appendimages'] : NULL;
  $im_rotateimage = isset($im['cf_imagemagick_opt_rotateimage']) ? $im['cf_imagemagick_opt_rotateimage'] : NULL;
  $im_sepiatoneimage = isset($im['cf_imagemagick_opt_sepiatoneimage']) ? $im['cf_imagemagick_opt_sepiatoneimage'] : NULL;

  $options = array();
  $options['cf_imfs'] = array(
    '#type' => 'fieldset',
    '#title' => 'ImageMagick',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $options['cf_imfs']['cf_imagemagick_opt_resizeimage'] = array(
    '#type' => 'textfield',
    '#title' => 'Resize Image',
    '#default_value' => $im_resizeimage,
    '#description' => 'Imagick::resizeImage(<i>x</i>, <i>y</i>, Imagick::FILTER_LANCZOS, 1). Make all images 800 pixels wide example: "<b>800, 0</b>"',
  );
  $options['cf_imfs']['cf_imagemagick_opt_rotateimage'] = array(
    '#type' => 'textfield',
    '#title' => 'Rotate Image',
    '#default_value' => $im_rotateimage,
    '#description' => 'Imagick::rotateImage(mixed $background, float $degrees). Rotate image 90deg example: "<b>#00000000, 90</b>"',
  );
  $options['cf_imfs']['cf_imagemagick_opt_setimagequality'] = array(
    '#type' => 'textfield',
    '#title' => 'Set Compression Quality',
    '#default_value' => $im_setcompressionquality,
    '#description' => 'Imagick::setCompressionQuality(int $quality). Compress image at 95% example: "<b>95</b>"',
  );
  $options['cf_imfs']['cf_imagemagick_opt_setresolution'] = array(
    '#type' => 'textfield',
    '#title' => 'Set Resolution',
    '#default_value' => $im_setresolution,
    '#description' => 'Imagick::setResolution(<i>x</i>, <i>y</i>). Use 300 by 300 dpi example: "<b>300, 300</b>"',
  );
  $options['cf_imfs']['cf_imagemagick_opt_sepiatoneimage'] = array(
    '#type' => 'textfield',
    '#title' => 'Sepia Tone Image',
    '#default_value' => $im_sepiatoneimage,
    '#description' => 'Imagick::sepiaToneImage(float $threshold). Sepia tone image at threshold 80 example: "<b>80</b>"',
  );

  // This should probably come last in the list.
  $options['cf_imfs']['cf_imagemagick_opt_appendimages'] = array(
    '#type' => 'textfield',
    '#title' => 'Append Images',
    '#default_value' => $im_appendimages,
    '#description' => 'Imagick::appendImages(bool $stack). Stack multiple images created by pdf conversion vertically example: "<b>1</b>"',
  );

  return $options;
}

/**
 * Transform exposed instance submission back to field instance like structure.
 *
 * @param array $form
 *   Form that the options have been exposed on.
 * @param array &$form_state
 *   Current values submitted by the form.
 * @param string $format
 *   Machine name of requested conversion format.
 *
 * @return array|bool
 *   An array formatted exactly as cf_imagemagick_options is. or NULL on error.
 *
 * @todo Create an alter hook for this, place another for actdual IM processing.
 * @see convertfile_options_exposed()
 * @see cf_imagemagick_options()
 */
function cf_imagemagick_options_exposed($form, &$form_state, $format = NULL) {
  $options = NULL;

  if (isset($form_state['values'])) {
    $values = $form_state['values'];
    foreach($values as $key => $value) {
      if (strpos($key, 'cf_imagemagick_opt') !== FALSE) {
        $options['cf_imfs'][$key] = $value;
      }
    }
  }

  return $options;
}

/**
 * Implements hook_help()
 */
function cf_imagemagick_help($path, $arg) {
  // If help is empty at end of function then NULL will be returned.
  $help = '';

  // Only use help if it is is still being requested.
  if (variable_get('cf_imagemagick_help', FALSE)) {
    if ($path == 'admin/config/convertfile/settings/provider/imagemagick') {

      $help .= '' .
      '<p>[<a href="https://github.com/delphian/drupal-convert-file/wiki/ImageMagick">Help Wiki</a>]</p>';

      // Helper text if ImageMagick PHP extension is missing.
      if (!class_exists('Imagick')) {
        $help .= '' .
          '<p>This provider requires the ImageMagick PHP extension to be installed.</p>' .
          '<p><a href="https://github.com/delphian/drupal-convert-file/wiki/Installing-ImageMagic-on-Mac-OSX-for-PHP-and-MAMP">https://github.com/delphian/drupal-convert-file/wiki/Installing-ImageMagic-on-Mac-OSX-for-PHP-and-MAMP</a></p>';
      }

    }
  }

  return (strlen($help)) ? $help : NULL;
}
