<?php

/**
 * @file
 * Provide a default conversion handler.
 */

/**
 * Implements of hook_menu().
 */
function cf_convertfile_menu() {
  // Provide a page to handle watchdog error messages.
  $items['admin/config/convertfile/settings/handler/convertfile'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Convert File',
    'description' => 'Default handler provided by Convert File module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cf_convertfile_form'),
    'access arguments' => array('administer convertfile settings'),
    'file' => 'cf_convertfile.admin.inc',
    'file path' => drupal_get_path('module', 'cf_convertfile'),
    'weight' => 40,
  );

  return $items;
}

/**
 * Implements hook_convertfile_info().
 *
 * Register our handler and formats with convertfile module.
 */
function cf_convertfile_convertfile_info() {
  $types = array(
    'gz' => '.gz (application/x-gzip)',
  );

  return array(
    'cf_convertfile' => array(
      'name' => 'Convert File',
      'types' => $types,
    ),
  );
}
