<?php

/**
 * @file
 * Convert File Handler that will convert using REST API from convertapi.com.
 */

/**
 * Implements of hook_menu().
 */
function cf_convertapi_menu() {
  // Provide a page to handle watchdog error messages.
  $items['admin/config/convertfile/settings/handler/convertapi'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'ConvertAPI.com',
    'description' => 'Convert files online with REST API from ConvertAPI.com',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cf_convertapi_form'),
    'access arguments' => array('administer convertfile settings'),
    'file' => 'cf_convertapi.admin.inc',
    'file path' => drupal_get_path('module', 'cf_convertapi'),
    'weight' => 40,
  );

  return $items;
}

/**
 * Implements hook_convertfile_info().
 *
 * Register our handler and formats with convertfile module.
 */
function cf_convertapi_convertfile_info() {
  $types = array();
  $types['cf_convertapi_pdf'] = '.pdf (application/pdf)';

  return array(
    'cf_convertapi' => array(
      'name' => 'ConvertAPI.com',
      'callback' => 'cf_convertapi_do_conversion',
      'types' => $types,
    ),
  );
}

function cf_convertapi_do_conversion($file, $instance) {
  $report = array();
  $settings = $instance['widget']['settings'];
  $dir = pathinfo($file->uri, PATHINFO_DIRNAME);
  $base = pathinfo($file->filename, PATHINFO_FILENAME);
  $ext = pathinfo($file->filename, PATHINFO_EXTENSION);
  $blob = file_get_contents($file->uri);
  $key = variable_get('cf_convertapi_api_key');
  $message = NULL;

  module_load_include('inc', 'cf_convertapi', 'cf_convertapi.api');
  if ($new_blob = cf_convertapi_api_call($file->uri, $key, $message)) {
    $fp = fopen($file->uri, "wbx");
    if (fwrite($fp, $body)) {
      $ext_new = 'pdf';
      $file->filename = $base . '.' . $ext . '.' . $ext_new;
      $file->filesize = filesize($file->uri);
      $file->filemime = file_get_mimetype($file->filename);
      $file->destination = $file->destination . '.' . $ext_new;
    }
    else {
      watchdog('convertfile', 'ConvertAPI could not write file to disk.', NULL, WATCHDOG_ERROR);
      $report[] = 'error';
    }
  }
  else {
    watchdog('convertfile', 'ConvertAPI could not convert file: @message.', array('@message' => $message), WATCHDOG_ERROR);
    $report[] = 'error';
  }

  return $report;
}
