<?php

/**
 * @file
 * File conversion provided by Google Drive SDK.
 */

/**
 * Implements of hook_menu().
 */
function cf_googledrive_menu() {
  // Provide a page to handle watchdog error messages.
  $items['admin/config/convertfile/settings/handler/googledrive'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Google Drive',
    'description' => 'File conversion provided by Google Drive.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cf_googledrive_form'),
    'access arguments' => array('administer convertfile settings'),
    'file' => 'cf_googledrive.admin.inc',
    'file path' => drupal_get_path('module', 'cf_googledrive'),
    'weight' => 40,
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function cf_googledrive_libraries_info() {
  // A very simple library. No changing APIs (hence, no versions), no variants.
  // Expected to be extracted into 'sites/all/libraries/simple'.
  $libraries['google-api-php-client'] = array(
    'name' => 'Google API PHP Client',
    'vendor url' => 'https://developers.google.com/drive/quickstart-php',
    'download url' => 'https://code.google.com/p/google-api-php-client/',
    'version' => 'none',
    'path' => 'src',
    'files' => array(
      'php' => array(
        'Google_Client.php',
        'contrib/Google_DriveService.php',
        'contrib/Google_Oauth2Service.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_convertfile_info().
 *
 * Register our provider and formats with convertfile module.
 */
function cf_googledrive_convertfile_info() {
  $types = array(
    'pdf' => '.pdf (application/pdf)',
    'txt' => '.txt (text/plain)',
  );

  return array(
    'cf_googledrive' => array(
      'name' => 'Google Drive',
      'types' => $types,
    ),
  );
}

/**
 * Implements hook_help()
 *
  * @see https://developers.google.com/drive/auth/web-server
 */
function cf_googledrive_help($path, $arg) {
  // If help is empty at end of function then NULL will be returned.
  $help = '';

  // Only use help if it is is still being requested.
  if (variable_get('cf_googledrive_help', FALSE)) {
    if ($path == 'admin/config/convertfile/settings/handler/googledrive') {

      // Helper text to create google application.
      if (!variable_get('cf_googledrive_client_id')) {
        $link = url($_GET['q'], array('absolute' => TRUE));
        $help .= '' .
          '<p>This module must use a google application to access the Google Drive service. Google will then check which individual users have granted the google application access to their Google Drive. The application must first be created at google. After creation, submit the app identification and secret key below so that drupal can authenticate itself as operating on behalf of this new application. Then you will be able to connect (authorize) an individual Google Drive account to this application.</p>' .
          '<ol>' .
          '  <li>Create an API project in the <a href="https://code.google.com/apis/console/">Google APIs Console</a>.</li>' .
          '  <li>Select the <b>Services</b> tab in your API project, and enable the Drive API <u>and</u> Drive SDK.</li>' .
          '  <li>Select the <b>API Access</b> tab in your API project, and click <b>Create an OAuth 2.0 client ID</b>.</li>' .
          '  <li>In the <b>Branding Information</b> section, provide a name for your application (e.g. "Drupal Convert File Google Drive Provider"), and click <b>Next</b>. Providing a product logo is optional.</li>' .
          '  <li>In the <b>Client ID Settings</b> section, do the following:</li>' .
          '  <ol>' .
          '    <li>Select <b>Web application</b> for the <b>Application type</b>.</li>' .
          '    <li>Click the <b>more options</b> link next to the heading, <b>Your site or hostname</b>.</li>' .
          '    <li>Enter ' . $link . ' in the <b>Authorized Redirect URIs</b> field. This must be a valid top level domain. Leave the javascript field empty.</li>' .
          '    <li>Click <b>Create Client ID</b>.</li>' .
          '  </ol>' .
          '  <li>In the <b>API Access</b> page, locate the section <b>Client ID for Web applications</b> and note the <b>Client ID</b> value.</li>' .
          '</ol><br>';
      }

      // Helper text when credentails are present but its not working for some reason.
      if (variable_get('cf_googledrive_credentials', FALSE) && !cf_googledrive_service(cf_googledrive_client())) {
        $help .= '<p>' . t('Application authorization may have been revoked. If you are having trouble with the connection please revoke the authorization if it still exists and try to connect again.') . '</p>' .
          '<ul>' .
          '  <li>Visit <a href="https://www.google.com/settings/security">https://www.google.com/settings/security</a>.</li>' .
          '  <li>Click on <b>Manage Access</b> beneath the Connected applications and sites</b> heading.</li>' .
          '  <li>Click on the <b>Revoke Access</b> button that follows <b>Drupal Convert File Google Drive Handler</b>.</li>' .
          '</ul>';
      }
    }
  }

  return (strlen($help)) ? $help : NULL;
}
