<?php

/**
 * @file
 * Convert File Handler that will compress files.
 */

/**
 * Implements of hook_menu().
 */
function cf_compress_menu() {
  // Provide a page to handle watchdog error messages.
  $items['admin/config/convertfile/settings/handler/compress'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Compress',
    'description' => 'Compress files.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cf_compress_form'),
    'access arguments' => array('administer convertfile settings'),
    'file' => 'cf_compress.admin.inc',
    'file path' => drupal_get_path('module', 'cf_compress'),
    'weight' => 40,
  );

  return $items;
}

/**
 * Implements hook_convertfile_info().
 *
 * Register our handler and formats with convertfile module.
 */
function cf_compress_convertfile_info() {
  $types = array();
  $types['cf_compress_gz'] = '.gz (application/x-gzip)';

  return array(
    'compress' => array(
      'name' => 'Compress',
      'types' => $types,
    ),
  );
}
